### ISSUE TITLE
Hey Ryan

### ISSUE THREAD

**Issue by lukefirth** [rdemello/rdemello.github.io#1]
eeee   eeeeee   zeeeeeeee.  4eeeec  4eeer                   
      $$$$   $$$$$"  4$$$$$$$$$b   $$$$$  4$$$F                
      $$$$  4$$$$P  .$$$$$$$$$$$L  "$$$$  ^$$$F              
      $$$$  J$$$$   $$$$$$$$$$$$$.  $$*$r  $$$F                   
      $$$P  $$$$"  d$$$$$$$$$$$$$$    d$L  $$$F                   
      $$$F  $$$P  z$$$$$$$$$$*"*$P   z$$$  $$$F                   
      $$$F 4$$$" 4$$$$$$$$$.    *"   ^$$$  $$$F                   
      $$$  d$$F .$$$P"    "$c       . *$$. $$$F                   
      $$$  $$$  *"$P       "$c     4b  $$F 3$$F                   
      $$$  $""    $   .e.   $$c    "$L "$$ 4$$F                   
      $$$ 4$      F   d$F   $$"     "$r $$ 4$$F                   
      $$P d$   ze$F   $$F   $P       "$.'$.'$$F                   
      $$F $"   """F   3$"   P   zc    "b *F $$F                   
      $$F.P       b    "   J"  .$$c  ..3L^$ $$F                   
      $$ 4"4   ..e$.      z"  .d$$$$$$$$$r3 $$F                   
      $$ F.$   $$$$$e....d$$$$$$***""""  ". $$F                   
      $$  d$   $$$$$$$***""""               $$F                   
      $$ d$$r***"""        .....eeeeP***e   *$F                   
      ""      ....ze===**""""""         ^*c  "F                   
      ===^"""""              ...........  ^*. "                   
      eeeeeeeeeee$$$$$$$$$$$$$$$$$$$$$$$bc. ^%.                   
      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$bc.                    
      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F                   
      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F                   
      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$F

**Comment by rdemello** [comment]
Hey Buddy ol pal
